import streamlit as st

def page_2(debug, agent, qa_system):
    st.markdown('<div class="header">Ask a question_</div>', unsafe_allow_html=True)
    st.text("")

    text = """
For a personalized response, adjust the settings of the **Llama-2-7b-chat-hf** model.

* **Expertise Level**: select an expertise level. `(Beginner, Intermediate, Advanced, Expert)`
* **Temperature**: adjust the creativity of the responses. `0.0 - deterministic and conservative responses; 1.0 - more varied and creative responses`
* **Max Tokens**: limit the number of tokens generated by the model *(per iteration)*.
* **Save**: save the conversation to see it later.
* **Download**: download the conversation history.
* **Reset**: reset session cache to start a new conversation.
    """
    st.write(text)
    st.write("___")

    agent.run_assistance(debug=debug, qa_system=qa_system)


